### ISSUE TITLE
3D implementation

### ISSUE THREAD

**Issue by WeileiZeng** [chaeyeunpark/UnionFind#1]
Very nice work! It is fun to run it! I can send some PR for python decoding demo with graphs in `pythonutil` if you are interested.

Is Kai Meinerz's python code open-source as well? And is there any implementation for 3D code?

Thanks!

**Comment by chaeyeunpark** [comment]
Thank you for your interest! Of course, you can send a PR. 

But as Kai's python code is more for an internal purpose, I don't think we open source it. However, I could find another python implementation at https://github.com/nanleij/The-toric-code. You may check it.

We expect adding 3D implementation is not super difficult but we leave all 3D things for the next work; thus I don't think we will add them in near future.

Best,
CY

**Comment by WeileiZeng** [comment]
Thanks! This's very helpful!

**Comment by chaeyeunpark** [comment]
As 3D implementation is added in f2a5fefa4d8724e496b48a7a2ca2a7fc7b3485b3, I close this issue.
