### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by ecpeterson** [chaeyeunpark/UnionFind#12]
Hello! At [top level](https://github.com/chaeyeunpark/UnionFind/blob/main/LICENSE), I see that the project has been licensed under LGPL. However, in the source code itself I see [header comments](https://github.com/chaeyeunpark/UnionFind/blob/main/UnionFindPy/cpp/include/LatticeFromParity.hpp#L5) stating it's licensed under GPL 3. Is this intentional?

**Comment by chaeyeunpark** [comment]
Oops. Thank you for pointing this out. LGPL is what I intended. I will fix the header comments soon.

**Comment by ecpeterson** [comment]
Wonderful. Thanks for explaining the intention!

**Comment by chaeyeunpark** [comment]
Closed by #13
